apiVersion: v1
kind: Service
metadata:
  name: research
  namespace: wmy
spec:
  selector:
    app: research
    version: dev
  type: NodePort
  externalIPs:
    - 192.168.1.114
  ports:
    - name: http
      port: 80
      nodePort: 31018
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: research
  namespace: wmy
spec:
  replicas: 1
  serviceName: research
  selector:
    matchLabels:
      app: research
      version: dev
  template:
    metadata:
      labels:
        app: research
        version: dev
        date: createdate
    spec:
      nodeSelector:
        node: node2
      containers:
        - name: research
          readinessProbe: # 就绪性探测
            tcpSocket:
              port: 80
            initialDelaySeconds: 20
            failureThreshold: 6
          livenessProbe: #存活性探测
            tcpSocket:
              port: 80
            initialDelaySeconds: 300
          image: registry.cn-shanghai.aliyuncs.com/wmy-backend/research-dev-release:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dev
                optional: false
          env:
            - name: appname
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
          volumeMounts:
            - name: logs
              mountPath: /logs # 日志
            - name: file
              mountPath: /home/file
            - name: customproject
              mountPath: /CodePackage
          ports:
            - name: research
              containerPort: 80
      volumes:
        - hostPath:
            path: /logs/
            type: DirectoryOrCreate
          name: logs
        - hostPath:
            path: /file
            type: DirectoryOrCreate
          name: file
        - hostPath:
            path: /customproject
            type: DirectoryOrCreate
          name: customproject

