version: '2'
services:
  training:
    # 内存限制10G,主要用于某些应用的限制防止无上限耗尽主机资源
    mem_limit: 11534336000
    image: registry.cn-shanghai.aliyuncs.com/wmy-backend/base
    environment:
      appname: training
      active: dev
      # eureka地址
      eureka: http://eureka/eureka/
      branch: develop_jykl
      curlargs: -x 10.2.177.11:8080
      argopts: --COURSE_HEART_CHECK=/el/study/heart_check --JYKL_HTTP_PROXY_URL=10.2.177.11 --JYKL_HTTP_PROXY_PORT=8080 --DEV_LIVE_CUSTOM_URI=http://gateway/web-manage/manage/live/public/auth
    stdin_open: true
    dns_search:
      - slb
    tty: true
    logging:
      driver: json-file
      options:
        max-size: 100m
    cpu_shares: 900
#    ports:
#      - 31026:80/tcp
    #cpus: 9
    volumes:
      - /home/file:/home/file
      - /customproject:/CodePackage
      - /logs:/LOG_PATH_IS_UNDEFINED
      - /logs:/logs
      - /logs:/app/logs
      - /jarfile:/jar
#    labels:
#      io.rancher.container.pull_image: always