From busybox
MainTainer 479100885@qq.com
ENV appname projectname
ENV ProjectPath /var/www/project/projectname
Copy dist.tar.gz /dist.tar.gz
Add start.sh /start.sh
ADD version.txt  version.txt
EntryPoint ["sh", "start.sh"]
