version: '2'
services:

  mysql:
    image: rancher/external-service
  redis:
    image: rancher/external-service
  rabbitmq:
    image: rancher/external-service
  elasticsearch:
    image: rancher/external-service
