apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: wmy
spec:
  selector:
    app: config
    version: dev
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: wmy
spec:
  selector:
    app: eureka
    version: dev
  type: ClusterIP
  clusterIP: None
  ports:
    - name: eureka
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: wmy
spec:
  selector:
    app: gateway
    version: dev
  type: NodePort
  ports:
    - name: gateway
      port: 8080
      nodePort: 32080
      targetPort: 80
