sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git eureka  'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git config  'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/cloud-aliyun.git aliyun 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/assignment-project.git assignment 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/cloud-certificate-group.git certificate 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/Course.git course 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/customproject.git customproject 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/sign-assignment-enroll.git enroll 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/cloud-esearch.git esearch 'develop_jykl'
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/exam-project.git exam 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git gateway  'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/cloud-job.git job 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/cloud-live.git live 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git log 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/cloud-web.git manage 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git message 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/point-project.git point 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/research-project.git research 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/sdk-project/shenwanhongyuan-project.git shenwanhongyuan 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/sign-project.git sign 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/site-project.git site 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/report/statistics.git statistics 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/cloud-web.git student 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/courses/cloud-course-studyLog.git studylog 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/elearn.git system  'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/training-project/training-project.git training  'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/vote-project.git vote 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/backend/examinations/weixin-project.git wechat 'develop_jykl' true
sh build3.sh ssh://git@g.km365.pw:122/frontend/admin.git admin 'jykl_admin' true
sh build3.sh ssh://git@g.km365.pw:122/frontend/student-h5.git student-h5 'jykl_h5' true
sh build3.sh ssh://git@g.km365.pw:122/frontend/wmyPc.git wmyPc 'jykl_pc' true
sh build3.sh ssh://git@g.km365.pw:122/backend/lecturer.git lecturer 'develop_jykl' true
