apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: middleware
  labels:
    app: mysql
spec:
  nodeName: mysql #固定调度到mysql节点，已打污点
  hostNetwork: true # 指定主机网络模式
  containers:
    - name: mysql
      image: mysql:5.6
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Yo^!3@LTvBJvtFHy
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqldata
      args:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --init-connect='SET NAMES UTF8'
  restartPolicy: Always
  volumes:
    - name: mysqldata
      hostPath:
        path: /var/lib/mysql
        type: DirectoryOrCreate

