apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  namespace: middleware
  labels:
    app: rabbitmq
spec:
  nodeName: mysql #固定调度到mysql节点，已打污点
  hostNetwork: true # 指定主机网络模式
  containers:
    - name: rabbitmq
      image: rabbitmq:3.7-management
      imagePullPolicy: IfNotPresent
      env:
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq.linuxs
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_VHOST
          value: /wmy

      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmqdata
  restartPolicy: Always
  volumes:
    - name: rabbitmqdata
      hostPath:
        path: /var/lib/rabbitmq
        type: DirectoryOrCreate

