apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: middleware
  labels:
    app: redis
spec:
  nodeName: mysql #固定调度到mysql节点，已打污点
  hostNetwork: true # 指定主机网络模式
  containers:
    - name: redis
      image: redis:4.0
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Yo^!3@LTvBJvtFHy
      volumeMounts:
        - mountPath: /data
          name: redisdata
      args:
        - --requirepass 'C2!LG!Ay$6qJiUWH'
#        - --appendonly yes  #开启同步
#        - appendfsync everysec #开启同步
  restartPolicy: Always
  volumes:
    - name: redisdata
      hostPath:
        path: /var/lib/redis/data
        type: DirectoryOrCreate

