FROM 10.23.1.161:8001/hongqiao/openjre8:latest
MAINTAINER Lu.Wu

#ADD target/website-api.jar app.jar
#RUN sh -c 'touch /app.jar'
RUN sh -c 'mkdir /logs'
ENV JAVA_OPTS="-Xms512M -Xmx1G"
ENV spring_profiles_active = test
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /app.jar --spring.profiles.active=$spring_profiles_active" ]

ADD jar /jar
ADD start.sh /start.sh
ADD version.txt  version.txt
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["sh","/start.sh"]