apiVersion: v1
kind: Namespace
metadata:
  name: wmy
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits-with-container
  namespace: wmy
spec:
  limits:
  - default: # 默认上限
      cpu: 8000m
      memory: 12000Mi
    defaultRequest: #默认保持
      cpu: 100m
      memory: 1000Mi
    max: # 最大上限
      cpu: "12"
      memory: 16000Mi
    min:
      cpu: 100m
    type: Container
